export const pivotData = [
    { rowType: "Tesla",  model: "Model Y", price: 123, electric: true , SAPvalue: 3456 , confirmed: true},
    { rowType: "Tesla",  model: "Model K", price: 33, electric: true, hasNote: true },
    { rowType: "Tesla",  model: "Model K", price: 456, electric: true , SAPvalue: 3456},
    { rowType: "Ford",   model: "F-Series", price: 3850, electric: false },
    { rowType: "Toyota", model: "Corolla", price: 29600, electric: false, hasNote: true },
    { rowType: "Tesla",  model: "Model H", price: 64950, electric: true , confirmed: true},
    { rowType: "Ford",   model: "F-Series 2", price: 33850, electric: false },
    { rowType: "Toyota", model: "Corolla", price: 29600, electric: false },
    { rowType: "Tesla",  model: "Model Z", price: 64950, electric: true },
    { rowType: "Ford",   model: "F-Series 3", price: 33850, electric: false },
    { rowType: "Toyota", model: "Corolla", price: 29600, electric: false },
    { rowType: "Tesla",  model: "Model Y", price: 64950, electric: true },
    { rowType: "Ford",   model: "F-Series", price: 33850, electric: false },
    { rowType: "Toyota", model: "Corolla", price: 29600, electric: false },
    { rowType: "Tesla",  model: "Model Y", price: 64950, electric: true },
    { rowType: "Ford",   model: "F-Series", price: 33850, electric: false },
    { rowType: "Toyota", model: "Corolla", price: 29600, electric: false },
    { rowType: "Tesla",  model: "Model Y", price: 64950, electric: true },
    { rowType: "Ford",   model: "F-Series", price: 33850, electric: false },
    { rowType: "Toyota", model: "Corolla", price: 29600, electric: false },
  ];